using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using RecipePlanner.Core.Recipes;
using RecipePlanner.Core.Stats;

namespace RecipePlanner.Core.Reporting
{
    /// <summary>
    /// Renders the cookbook and the production record as human-readable Markdown.
    ///
    /// This exists because of an asymmetry in what the mod can offer: production tracking works on
    /// both Steam branches, but the phone app is Mono-only. Without this, a player on the default
    /// branch installs the mod, plays, and sees nothing at all — the data lands in `events.jsonl`
    /// and `stats.json`, which are not something anyone wants to read. A background service is not
    /// a mod. This gives every player something to open regardless of branch.
    ///
    /// Pure: no I/O, no game types, no clock of its own. Everything it needs is passed in, which is
    /// what makes it testable without launching anything.
    ///
    /// Money is deliberately *omitted* rather than shown as 0 when prices could not be read. A
    /// confident "$0 profit" is a wrong answer; "not available" is a true one. See
    /// GamePriceSource — the same failure is what makes this distinction necessary.
    /// </summary>
    public static class CookbookReport
    {
        private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

        public static string Render(
            string profileLabel,
            PlayerStatistics stats,
            IEnumerable<Recipe> recipes,
            DateTime generatedUtc)
        {
            var sb = new StringBuilder();
            var all = (recipes ?? Enumerable.Empty<Recipe>()).Where(r => r != null).ToList();
            stats = stats ?? new PlayerStatistics();

            Header(sb, profileLabel, generatedUtc);
            Totals(sb, stats);
            Products(sb, stats);
            Recipes(sb, all, stats);
            Ingredients(sb, stats);
            Records(sb, stats);
            Excluded(sb, stats);

            sb.Append("\n---\n\nGenerated by Schedule I Cookbook. This file is rewritten automatically; ")
              .Append("edits will be lost. Your game saves are never modified.\n");

            return sb.ToString();
        }

        private static void Header(StringBuilder sb, string profileLabel, DateTime generatedUtc)
        {
            sb.Append("# Cookbook — ").Append(Safe(profileLabel, "Unknown character")).Append("\n\n");
            sb.Append("Generated ")
              .Append(generatedUtc.ToString("yyyy-MM-dd HH:mm", Inv))
              .Append(" UTC\n");
        }

        private static void Totals(StringBuilder sb, PlayerStatistics stats)
        {
            var t = stats.Personal ?? new Totals();

            sb.Append("\n## Totals\n\n");
            sb.Append("| | |\n|---|---|\n");
            Row(sb, "Units produced", Num(t.UnitsProduced));
            Row(sb, "Batches", Num(t.Batches));
            Row(sb, "Unique recipes produced", Num(stats.UniqueRecipesProduced));
            Row(sb, "Events recorded", Num(stats.EventsFolded));

            if (HasMoney(t))
            {
                Row(sb, "Value", Money(t.TotalValue));
                Row(sb, "Cost", Money(t.TotalCost));
                Row(sb, "Estimated profit", Money(t.EstimatedProfit));
            }
            else
            {
                sb.Append("\n> Monetary figures are not available — the mod could not read the ")
                  .Append("game's price table this session. Everything above is unaffected.\n");
            }

            var byType = stats.ByDrugType;
            if (byType == null || byType.Count == 0) return;

            sb.Append("\n### By drug type\n\n| Type | Units | Batches |\n|---|---:|---:|\n");
            foreach (var pair in byType.OrderByDescending(p => p.Value?.UnitsProduced ?? 0))
            {
                var v = pair.Value ?? new Totals();
                sb.Append("| ").Append(Safe(pair.Key, "?"))
                  .Append(" | ").Append(Num(v.UnitsProduced))
                  .Append(" | ").Append(Num(v.Batches))
                  .Append(" |\n");
            }
        }

        private static void Products(StringBuilder sb, PlayerStatistics stats)
        {
            var products = Ordered(stats.ByProduct, p => p.Units);
            if (products.Count == 0) return;

            var money = products.Any(p => p.Value > 0 || p.Cost > 0);

            sb.Append("\n## Products\n\n| Product | Units | Batches | Last made");
            if (money) sb.Append(" | Value | Profit");
            sb.Append(" |\n|---|---:|---:|---|");
            if (money) sb.Append("---:|---:|");
            sb.Append("\n");

            foreach (var p in products)
            {
                sb.Append("| ").Append(Safe(p.DisplayName, p.ProductId))
                  .Append(" | ").Append(Num(p.Units))
                  .Append(" | ").Append(Num(p.Batches))
                  .Append(" | ").Append(Date(p.LastProducedUtc));
                if (money) sb.Append(" | ").Append(Money(p.Value)).Append(" | ").Append(Money(p.Profit));
                sb.Append(" |\n");
            }
        }

        /// <summary>
        /// Recipes grouped by the base product they descend from, which is how the phone app shows
        /// them and how players think about them — "my OG Kush line", not an alphabetical list.
        /// Hidden recipes are omitted, matching the in-game view exactly; they keep their history.
        /// </summary>
        private static void Recipes(StringBuilder sb, List<Recipe> recipes, PlayerStatistics stats)
        {
            var visible = recipes.Where(r => !r.IsHidden).ToList();
            if (visible.Count == 0)
            {
                sb.Append("\n## Recipes\n\nNothing discovered yet.\n");
                return;
            }

            sb.Append("\n## Recipes\n\n")
              .Append(Num(visible.Count)).Append(" recipe(s)");

            var hidden = recipes.Count - visible.Count;
            if (hidden > 0) sb.Append(", plus ").Append(Num(hidden)).Append(" hidden");
            sb.Append(".\n");

            var groups = visible
                .GroupBy(r => Safe(r.BaseProductId, "(unknown base)"), StringComparer.OrdinalIgnoreCase)
                .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase);

            foreach (var group in groups)
            {
                sb.Append("\n### ").Append(group.Key).Append("\n\n");

                foreach (var r in group.OrderByDescending(r => r.TimesProduced)
                                       .ThenBy(r => Safe(r.Name, r.RecipeId), StringComparer.OrdinalIgnoreCase))
                {
                    sb.Append("- **").Append(Safe(r.Name, r.RecipeId)).Append("**");

                    if (r.Has(RecipeStatus.Favourite)) sb.Append(" ⭐");

                    // The chain is the point: base -> step -> step is how the product was built.
                    var steps = (r.Steps ?? new List<string>()).Where(s => !string.IsNullOrEmpty(s)).ToList();
                    if (steps.Count > 0)
                        sb.Append("\n  - Chain: ").Append(group.Key).Append(" → ").Append(string.Join(" → ", steps));

                    var effects = (r.Effects ?? new List<string>()).Where(e => !string.IsNullOrEmpty(e)).ToList();
                    if (effects.Count > 0)
                        sb.Append("\n  - Effects: ").Append(string.Join(", ", effects));

                    if (r.TimesProduced > 0)
                    {
                        sb.Append("\n  - Made ").Append(Num(r.TimesProduced)).Append(" time(s)");

                        RecipeStat stat = null;
                        if (stats.ByRecipe != null && r.RecipeId != null)
                            stats.ByRecipe.TryGetValue(r.RecipeId, out stat);

                        if (stat != null)
                        {
                            sb.Append(", ").Append(Num(stat.UnitsProduced)).Append(" unit(s)");
                            if (stat.TotalValue > 0) sb.Append(", worth ").Append(Money(stat.TotalValue));
                        }
                        if (r.LastProducedUtc.HasValue)
                            sb.Append(" — last ").Append(Date(r.LastProducedUtc.Value));
                    }

                    sb.Append("\n");
                }
            }
        }

        private static void Ingredients(StringBuilder sb, PlayerStatistics stats)
        {
            var used = Ordered(stats.ByIngredient, i => i.UnitsConsumed);
            if (used.Count == 0) return;

            var money = used.Any(i => i.TotalCost > 0);

            sb.Append("\n## Ingredients used\n\n| Ingredient | Times | Units");
            if (money) sb.Append(" | Cost");
            sb.Append(" |\n|---|---:|---:|");
            if (money) sb.Append("---:|");
            sb.Append("\n");

            foreach (var i in used)
            {
                sb.Append("| ").Append(Safe(i.IngredientId, "?"))
                  .Append(" | ").Append(Num(i.TimesUsed))
                  .Append(" | ").Append(Num(i.UnitsConsumed));
                if (money) sb.Append(" | ").Append(Money(i.TotalCost));
                sb.Append(" |\n");
            }
        }

        private static void Records(StringBuilder sb, PlayerStatistics stats)
        {
            var r = stats.Records;
            if (r == null) return;

            // Records hold ids, and an id is not an answer: "r1" or "extremeassblaster" tells the
            // player nothing. Resolve through the stats tables, which already carry the names the
            // game shows, and fall back to the id only when there is nothing better.
            var lines = new List<string>();
            Add(lines, "Most used recipe", RecipeName(stats, r.MostUsedRecipeId));
            Add(lines, "Most produced product", ProductName(stats, r.MostProducedProductId));
            Add(lines, "Most used ingredient", r.MostUsedIngredientId);
            Add(lines, "Highest value recipe", RecipeName(stats, r.HighestValueRecipeId));
            Add(lines, "Most profitable recipe", RecipeName(stats, r.MostProfitableRecipeId));

            if (r.LargestBatchUnits > 0)
            {
                var of = ProductName(stats, r.LargestBatchProductId);
                lines.Add("- Largest batch: " + Num(r.LargestBatchUnits) + " unit(s)"
                          + (string.IsNullOrEmpty(of) ? "" : " of " + of));
            }

            if (lines.Count == 0) return;

            sb.Append("\n## Records\n\n");
            foreach (var line in lines) sb.Append(line).Append("\n");
        }

        /// <summary>
        /// Employee cooks and other players' work are recorded but kept out of personal totals.
        /// Reporting them matters: a player who sees a lower number than they expected needs to
        /// know it was a deliberate exclusion and not a miscount.
        /// </summary>
        private static void Excluded(StringBuilder sb, PlayerStatistics stats)
        {
            var e = stats.Excluded;
            if (e == null || (e.UnitsProduced == 0 && e.Batches == 0)) return;

            sb.Append("\n## Not counted as yours\n\n")
              .Append(Num(e.UnitsProduced)).Append(" unit(s) across ").Append(Num(e.Batches))
              .Append(" batch(es) were recorded but kept out of the totals above.\n");

            if (stats.ExcludedByReason == null || stats.ExcludedByReason.Count == 0) return;

            sb.Append("\n| Reason | Events |\n|---|---:|\n");
            foreach (var pair in stats.ExcludedByReason.OrderByDescending(p => p.Value))
                sb.Append("| ").Append(pair.Key).Append(" | ").Append(Num(pair.Value)).Append(" |\n");
        }

        // ---- helpers ----

        private static bool HasMoney(Totals t) => t.TotalValue > 0 || t.TotalCost > 0;

        private static string RecipeName(PlayerStatistics stats, string recipeId)
        {
            if (string.IsNullOrEmpty(recipeId) || stats.ByRecipe == null) return recipeId;
            RecipeStat stat;
            return stats.ByRecipe.TryGetValue(recipeId, out stat) && stat != null
                ? Safe(stat.DisplayName, recipeId)
                : recipeId;
        }

        private static string ProductName(PlayerStatistics stats, string productId)
        {
            if (string.IsNullOrEmpty(productId) || stats.ByProduct == null) return productId;
            ProductStat stat;
            return stats.ByProduct.TryGetValue(productId, out stat) && stat != null
                ? Safe(stat.DisplayName, productId)
                : productId;
        }

        private static List<T> Ordered<T>(Dictionary<string, T> map, Func<T, long> by) =>
            map == null
                ? new List<T>()
                : map.Values.Where(v => v != null).OrderByDescending(by).ToList();

        private static void Add(List<string> lines, string label, string value)
        {
            if (!string.IsNullOrEmpty(value)) lines.Add("- " + label + ": " + value);
        }

        private static void Row(StringBuilder sb, string label, string value) =>
            sb.Append("| ").Append(label).Append(" | ").Append(value).Append(" |\n");

        private static string Num(long n) => n.ToString("N0", Inv);

        private static string Money(double d) => "$" + d.ToString("N2", Inv);

        private static string Date(DateTime utc) =>
            utc == default(DateTime) ? "—" : utc.ToString("yyyy-MM-dd", Inv);

        private static string Safe(string value, string fallback) =>
            string.IsNullOrWhiteSpace(value) ? fallback : value;
    }
}
